### ISSUE TITLE
Unguarded call to `__main__.__file__` leading to `AttributeError` in interactive use

### ISSUE THREAD

**Issue by Edenhofer** [Ockenfuss/inlog#1]
The following code
```python
import inlog

config = inlog.load_ini('config.ini',version='1.0')
str(config)
```
raises an `AttributeError` if executed in an interactive python session.

**Comment by Ockenfuss** [comment]
True, thanks for reporting! I commited 470d95e to fix this. (Setting the source file path to None/null in the log if the `__file__` attribute is not accessible).

**Comment by Edenhofer** [comment]
Patch looks good! 👍 You might consider using getattr though :)

**Comment by Ockenfuss** [comment]
You mean `getattr(__main__, '__file__', None)`? True, I haven't thought of this! However, the try-except allows to implement alternatives in the future, if the `__file__` approach fails. This I haven`t done so far, but there would be several alternative options (https://stackoverflow.com/a/35514032)

**Comment by Edenhofer** [comment]
Yes, exactly. There are multiple ways to achieve the same with `getattr` and/or `hasattr` and some `if/else` logic but `try/except` of course works too. I like to avoid `try/except` blocks whenever it is easy to replace them with `if/else` blocks though this is probably a matter of personal taste :)
